### ISSUE TITLE
.h file not found error

### ISSUE THREAD

**Issue by avsingh999** [RonanB96/Displacement-from-accelerometer#1]
#### I am running  accel4.ino but i am getting this error

Arduino: 1.8.5 (Windows 10), Board: "Arduino/Genuino Uno"

Build options changed, rebuilding all
In file included from C:\Users\Av Singh\Desktop\Displacement-from-accelerometer\Accel4\Accel4.ino:22:0:

sketch\Timer.h:24:21: fatal error: Energia.h: No such file or directory

 #include <Energia.h>

                     ^

compilation terminated.

exit status 1
Error compiling for board Arduino/Genuino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

#### can you please help me?

**Comment by ronanbyrne96** [comment]
Hi,
The code in this repo is actually for Texas instruments boards (only tested on MSP432) and uses the Energia IDE to program them so the code will not work on an Arduino.
[ http://energia.nu/](http://energia.nu/ )

To use an Arduino, you will need to use a different timer library and change the accel4.ino code to work with it

**Comment by per1234** [comment]
If it's not compatible with Arduino, the `arduino` topic you added to the repository seems inappropriate.

**Comment by RonanB96** [comment]
You're right, I removed the arduino topic

**Comment by avsingh999** [comment]
thanks @ronanbyrne96  @per1234  @RonanB96
