### ISSUE TITLE
time cannot be resolved to a variable

### ISSUE THREAD

**Issue by popado** [RonanB96/Displacement-from-accelerometer#2]
Hi,

At line 354: time = hour()+"_" + minute()+" "+day()+"-"+month()+"-"+year();

give me an error: "time cannot be resolved to a variable".

How can I resolve ?

Thanks.

PopaD.

**Comment by RonanB96** [comment]
Try compile it now, merged in a small fix which allowed it to compile, haven't got to do a run through of the system in a long while. Plan to do a total rework of repo in the future

**Comment by popado** [comment]
It's ok now, Thank you. Great job !
